export const CONVERT_FROM_DECIMAL = 'CONVERT_FROM_DECIMAL';
export const CONVERT_FROM_HEXADECIMAL = 'CONVERT_FROM_HEXADECIMAL';
export const CONVERT_FROM_BINARY = 'CONVERT_FROM_BINARY';
export const CONVERT_FROM_BASE64 = 'CONVERT_FROM_BASE64';
